# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friended_by',
            field=models.ManyToManyField(default=False, related_name='friends', to='login_reg.User'),
        ),
    ]
